# Generated by Django 5.0.14 on 2026-08-16 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('current_level', models.PositiveIntegerField(default=0)),
                ('completed_levels', models.JSONField(blank=True, default=list)),
                ('is_finished', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='catalog.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'game progress',
            },
        ),
        migrations.AddConstraint(
            model_name='gameprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('game', 'user'), name='uniq_progress_game_user'),
        ),
        migrations.AddConstraint(
            model_name='gameprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('session_key', ''), _negated=True)), fields=('game', 'session_key'), name='uniq_progress_game_session'),
        ),
    ]
