# Generated by Django 5.0.14 on 2026-08-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, help_text="Image de couverture affichée sur la carte d'accueil.", null=True, upload_to='games/covers/'),
        ),
    ]
