# Generated by Django 5.0.14 on 2026-09-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_game_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='hint',
            field=models.TextField(blank=True, help_text='Indice technique débloquable.'),
        ),
        migrations.AddField(
            model_name='level',
            name='scene',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='level',
            name='objective',
            field=models.TextField(help_text="Texte d'énigme affiché au joueur."),
        ),
    ]
